---
# LEAF3 specific data model

# Interfaces

# VLANs
vlans:
  - id: 20
    name: "twenty"

interfaces:
  Ethernet1:
    descr: "To_Spine1"
    mode: "trunk"
  Ethernet2:
    descr: "To_Spine2"
    mode: "trunk"
  Ethernet10:
    descr: "Host2"
    mode: "access"
    vlan: 20
  Ethernet48:
    descr: "To_Leaf4"
    mode: "trunk"
