---
# SPINE2 specific data model

# Interfaces

# VLANs
vlans:
  - id: 10
    name: "ten"
  - id: 20
    name: "twenty"

svis:
  - id: 10
    desc: "ten"
    host_ip: "10.10.10.3/24"
    vip: "10.10.10.1"
  - id: 20
    desc: "twenty"
    host_ip: "20.20.20.3/24"
    vip: "20.20.20.1"
